name: pokemon_example
version: 0.0.1

authors:
  - Igor Borges <igor@borges.me>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3

dev_dependencies:
  test: ^1.17.8
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  artemis:
    path: ../../.
